### ISSUE TITLE
TelnyxWebhook<OutboundMessage> Object is not Mapped with V2 Webhook Response 

### ISSUE THREAD

**Issue by ajaysingh77** [team-telnyx/telnyx-dotnet#30]
If Messaging Profile is of Type "Twexit" the webhook response contains "FROM" property like this
"from": {
        "carrier": "Telnyx",
        "line_type": "Wireless",
        "phone_number": "+17085XXXXX"
      }

If Messaging Profile is of Type "V2" the webhook response contains "FROM" property like this

"from": "+170857XXXXX"

This difference is causing the issue when mapping the object to TelnyxWebhook<OutboundMessage> in callback.
Is there somewhere property for V2 API or I need to change the .Net SDK code to fix this.

Also "OutboundMessage" type is missing the following properties
"messaging_profile_id"
"organization_id".

**Comment by d-telnyx** [comment]
@ajaysingh77 Thank you you bringing it up! 

Noted the missing parameters, we'll get those added ASAP. 

With regards to the object/string, I'll take a look to see what we can do.

**Comment by d-telnyx** [comment]
@ajaysingh77 can you please contact support by visiting the [portal](https://portal.telnyx.com/) and clicking the button in the bottom right 
![image](https://user-images.githubusercontent.com/68876596/96650892-ad667480-1301-11eb-849a-8cff814615d1.png)

And link the support team to this thread so they have context. Thanks!

**Comment by ajaysingh77** [comment]
On more observations, No matter whether it's V2 or Twexit API version, 
`TelnyxWebhook<OutboundMessage>  ` object is not mapped to Webhook response from Telnyx.

`TelnyxWebhook<OutboundMessage> ` object is mapped to documentation `https://developers.telnyx.com/docs/v2/messaging/receiving-webhooks` 
but not to actual response which Telnyx Webhook is sending, which is causing the following code to fail.

`public async Task<IActionResult> Post([FromBody] TelnyxWebhook<OutboundMessage> telnyxMessage, string ClientCode)
        {
`

**Comment by d-telnyx** [comment]
@ajaysingh77 were you able to get your account migrated to the proper version of the Messaging v2 API?

**Comment by d-telnyx** [comment]
@ajaysingh77 closing for now; let me know if you were unable to get ahold of support
