### ISSUE TITLE
Event types & Delivery Status

### ISSUE THREAD

**Issue by Durkee** [team-telnyx/telnyx-dotnet#4]
What are all of the Event Types and Delivery Statuses?  Can we get all of them in enums please?  A Webhook example would help along with the various models.  I think I saw 3: incoming message, event notification such as message delivered, and Url click event.  Thank you

**Comment by thedonmon** [comment]
@Durkee event types and delivery statuses have been added via PR

**Comment by Durkee** [comment]
Thank you

**Comment by Durkee** [comment]
Can you create a list of constants list such as TOLL_FREE = "toll-free"?  This would be great as an enum and then you convert to string if needed. 
I am doing a Number Search and I find the property below to pass in only when it's a toll free number.  What about a local number?  
`NumberSearchOptions `
`public string NumberType { get; set; }`
