### ISSUE TITLE
Programmable Fax

### ISSUE THREAD

**Issue by wahmedswl** [team-telnyx/telnyx-dotnet#62]
Hi,
Can we send data url as ```media_url``` in Programmable Fax? Rather than having public url for the pdf, can we send pdf as Base64 using data urls. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

Thanks

**Comment by ADandyGuyInSpace** [comment]
Currently, we only support what is found here: https://developers.telnyx.com/api/programmable-fax/send-fax

Essentially if you want a private url, you can upload it to our media API then hit it from the Fax API to send that specific PDF. We do not support the data-stream method as of yet
