### ISSUE TITLE
Heavy CPU usage?

### ISSUE THREAD

**Issue by Thorium** [team-telnyx/telnyx-dotnet#64]
Just a question...
What is the dependency to: Rebex.Elliptic.Ed25519
After adding the Telnyx client, the server CPU jumped significantly.

Are you mining Bitcoins in the client?

**Comment by ADandyGuyInSpace** [comment]
Ed25519 is a public-key signature method for cryptography: https://ed25519.cr.yp.to/. Our webhook signatures and the like are verified as such. More info at the bottom here: https://support.telnyx.com/en/articles/4334722-how-to-leverage-webhooks#h_4a98d6c1d5

Unfortunately, not that kind of crypto.
