### ISSUE TITLE
No way to retrieve call info

### ISSUE THREAD

**Issue by Maxwell175** [team-telnyx/telnyx-dotnet#72]
I cannot seem to find a way to retrieve the call info currently:

https://developers.telnyx.com/openapi/callcontrol/tag/Call-Information/#tag/Call-Information/operation/retrieveCallStatus

**Comment by chiptech-mitchell** [comment]
If you are still interested, there is now unreleased code for this endpoint in the master branch [here.](https://github.com/team-telnyx/telnyx-dotnet/blob/9e9fbb4108f62e64d36c328231972aca139c903b/src/Telnyx.net/Services/Calls/CallControl/Dial/CallControlDialService.cs#L44)

**Comment by vionash** [comment]
Resolved in latest update
