### ISSUE TITLE
The CallControlService is missing Gather API

### ISSUE THREAD

**Issue by troutkilroy** [team-telnyx/telnyx-dotnet#76]
The CallControlService has Gather with audio & speak APIs, but it's missing the plain Gather command as outlined here:

https://developers.telnyx.com/openapi/callcontrol/tag/Call-Commands/#tag/Call-Commands/operation/callGather

**Comment by troutkilroy** [comment]
I added a pull for this:

https://github.com/team-telnyx/telnyx-dotnet/pull/77

**Comment by ADandyGuyInSpace** [comment]
Merged this in
